# Generated by Django 3.2.7 on 2021-11-04 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='quiz', max_length=60)),
                ('description', models.CharField(default='description', max_length=160)),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
    ]
