# Generated by Django 3.2.7 on 2021-11-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20211104_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
