# Generated by Django 3.2.7 on 2021-11-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_quiz_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='Question Body', max_length=160)),
                ('answer', models.CharField(default='Answer Body', max_length=250)),
                ('quizID', models.IntegerField()),
            ],
        ),
    ]
